
(defvar *proc*)

(defun hunt ()
  (dotimes (run 10000)
    (run-program "/usr/bin/rm" `("-rf" "/home/wade/.local/share/rr"))
    (let ((*proc* (run-program "/usr/bin/rr" `("record" "-c" "20" "a") 
			       :output t :wait nil)))
      (print *proc*)
      (terpri)
      (dotimes (time 20)
        (sleep 60)
	(let ((status (process-status *proc*)))
	  (unless (process-alive-p *proc*)
	    (format t "~%*******Program died with ~S!*****~%" status)
	    (return-from hunt 'done))
	  (print status)
	  (terpri)))
      (process-kill *proc* 9 :pid))))
