
(defvar *proc*)

(defun hunt ()
  (dotimes (run 3)
    (run-program "/usr/bin/rm" `("-rf" "/home/wade/.local/share/rr"))
    (let ((*proc* (run-program "/usr/bin/rr" `("record" "a") 
			       :output t :wait nil)))
      (print *proc*)
      (terpri)
      (dotimes (time 3)
        (sleep 10)
	(let ((status (process-status *proc*)))
	  (unless (process-alive-p *proc*)
	    (format t "~%*******Program died with ~S!*****~%" status)
	    (return-from hunt 'done))
	  (print status)
	  (terpri)))
      (process-kill *proc* 9 :pid))))
